### ISSUE TITLE
Possible revision with USB-C

### ISSUE THREAD

**Issue by vitalykorolev** [evyd13/atom47#5]
Just noticed that there is rev5 of the PCB. How hard would it be to design a version with USB-C port instead of micro USB?

**Comment by evyd13** [comment]
Wouldn't be difficult at all, but it would break compatibility with the Vortex Core case.

**Comment by vitalykorolev** [comment]
True, but if it's in the same location, then the hole needs to be just a bit bigger. My case is already modified as I tried to replace the port on my board. Unfortunately, I failed and now looking for a replacement board.

**Comment by evyd13** [comment]
I made a usb-c version locally, here's the difference in PCB footprint:
![image](https://user-images.githubusercontent.com/17366381/155806882-94741710-b587-418d-9ae0-01c95e1b63aa.png)

Are you sure this will work?

**Comment by vitalykorolev** [comment]
I don't see why not. I'd have to make the hole a bit bigger to fit the new port, but it's a small sacrifice for a hugely more convenient standard. It'd be interesting to see if there are a few others who would be interested in this so that ordering PCBs would make sense.

**Comment by evyd13** [comment]
https://github.com/evyd13/atom47/tree/master/pcb-files/rev5-c

Here you go! Re-open the issue if needed.
